version: 2

sources:
  - name: spotify
    schema: raw
    description: "Raw ingested data from Spotify listening history."
    tables:
      - name: raw_history
        description: "JSON snapshots captured by the Python ingest workflow."
        loaded_at_field: collected_at
        freshness:
          warn_after:
            count: 3
            period: hour
          error_after:
            count: 6
            period: hour
  - name: spotify_staging
    schema: staging
    description: "Staging tables for processed data."
    tables:
      - name: artists
        description: "Artist metadata fetched from Spotify API."

